#!/bin/bash

# League Dashboard Environment Setup Script
# This script helps set up environment files for both backend and frontend

echo "🚀 League Dashboard Environment Setup"
echo "===================================="

# Check if env.template exists
if [ ! -f "env.template" ]; then
    echo "❌ Error: env.template not found in the current directory"
    echo "Please run this script from the root of the league_dashboard project"
    exit 1
fi

# Setup backend environment
echo "📝 Setting up backend environment..."
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists. Creating backup..."
    cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
fi

cp env.template .env
echo "✅ Created .env from template"

# Setup frontend environment
echo "📝 Setting up frontend environment..."
cd frontend

if [ -f ".env.local" ]; then
    echo "⚠️  frontend/.env.local already exists. Creating backup..."
    cp .env.local .env.local.backup.$(date +%Y%m%d_%H%M%S)
fi

# Create frontend environment file
cat > .env.local << EOF
# Frontend Environment Configuration
# This file was auto-generated by setup-env.sh

# API Base URL - Configure this to point to your backend API
# For local development: http://localhost:8080/api
# For production: https://your-domain.com/api
REACT_APP_API_BASE_URL=http://localhost:8080/api
EOF

echo "✅ Created frontend/.env.local"
cd ..

echo ""
echo "🎉 Environment setup complete!"
echo ""
echo "Next steps:"
echo "1. Edit .env and add your Riot API key and other configuration"
echo "2. Edit frontend/.env.local if you need to change the API URL"
echo "3. Make sure MongoDB and Redis are running"
echo "4. Run 'npm run dev' to start the application"
echo ""
echo "📚 For more information, see:"
echo "   - README.md (main documentation)"
echo "   - frontend/README.env.md (frontend environment details)" 